### PR TITLE
Examples in documentations

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
Small PR to add the tutorial to the documentation

### CODE REVIEW

**Comment by jhdark** [comment]
Now that we have the workshop and have linked in the docs, where does that leave us with the demos in the repo? Are they worth keeping in there?

**Comment by RemDelaporteMathurin** [comment]
> Now that we have the workshop and have linked in the docs, where does that leave us with the demos in the repo? Are they worth keeping in there?

Was thinking about that. We could maybe remove them

**Comment by jhdark** [comment]
Perhaps we could have them in pure python scripts and integrate them into the system tests? But other than that don't see much of a use for them

**Comment by RemDelaporteMathurin** [comment]
> Perhaps we could have them in pure python scripts and integrate them into the system tests? But other than that don't see much of a use for them

It wouldn't bring anything to integrate them to the tests. 
We can remove them in another PR.

**Review by jhdark — APPROVED** [review]
Looks good to me

**Pull request merged**
